# Generated by Django 5.1.6 on 2025-02-23 20:10

import django.db.models.deletion
import django_summernote.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Esse campo deve ser marcado para tornar a página publica')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('number_store', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numero da Loja')),
                ('title', models.CharField(max_length=50, verbose_name='Nome da Loja')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='WhatsApp')),
                ('text', models.TextField(blank=True, default='Estou interessado no produto: ', max_length=255, null=True, verbose_name='Mensagem WhatsApp')),
                ('store_manager', models.CharField(max_length=100, verbose_name='Gerente')),
                ('text_link', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Código', models.IntegerField(default=None, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=50, verbose_name='Produto')),
                ('slug', models.SlugField(default=None, unique=True)),
                ('excerpt', models.CharField(max_length=150, verbose_name='Descrição curta')),
                ('cover', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('vitrine_link', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Esse campo deve ser marcado para tornar o post publico')),
                ('old_price', models.FloatField(verbose_name='Preço De:')),
                ('new_price', models.FloatField(verbose_name='Preço Por:')),
                ('offer_validity', models.DateField(blank=True, null=True, verbose_name='Validade da oferta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_link', models.CharField(blank=True, default='', editable=False, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabloide.category', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_updated_by', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, default='', to='tabloide.tag')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
