# Generated by Django 5.1.6 on 2025-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='WhatsApp'),
        ),
    ]
