# Generated by Django 5.1.6 on 2025-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='Código',
            field=models.BigAutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
