# Generated by Django 5.1.6 on 2025-02-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0002_alter_store_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='text_link',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
