# Generated by Django 5.1.6 on 2025-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0002_remove_post_id_post_código'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Código',
            field=models.DecimalField(decimal_places=0, default=None, editable=False, max_digits=7, primary_key=True, serialize=False),
        ),
    ]
