# Generated by Django 5.1.6 on 2025-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0003_store_text_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
