# Generated by Django 5.1.6 on 2025-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0003_alter_post_código'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Código',
            field=models.BigAutoField(db_index=True, default=None, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
    ]
