# Generated by Django 5.1.6 on 2025-02-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0004_alter_post_código'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_store', models.IntegerField(verbose_name='Numero da Loja')),
                ('title', models.CharField(max_length=50, verbose_name='Nome da Loja')),
                ('phone_number', models.IntegerField(verbose_name='WhatsApp')),
                ('text', models.TextField(blank=True, default='Estou interessado no produto: ', max_length=255, null=True, verbose_name='Mensagem WhatsApp')),
                ('store_manager', models.CharField(max_length=100, verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Código', models.IntegerField(default=None, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('Nome do Produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('slug', models.SlugField(default='', unique=True)),
                ('Descrição curta', models.CharField(max_length=150, verbose_name='Descrição curta')),
                ('cover', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('vitrine_link', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Esse campo deve ser marcado para tornar o post publico')),
                ('Preço De:', models.FloatField(verbose_name='Preço De:')),
                ('Preço Por:', models.FloatField(verbose_name='Preço Por:')),
                ('Validade da oferta', models.DateField(blank=True, null=True, verbose_name='Validade da oferta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabloide.category', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_created_by', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, default='', to='tabloide.tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
