# Generated by Django 5.1.6 on 2025-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0004_product_text_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text_link',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True),
        ),
    ]
